version: '2'

services:
  nginx:
    image: nginx:1.15.7
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  web:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    env_file:
        - web-variables.env
    command: sh start-api.sh
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:5.0.3
    restart: always
    volumes:
      - ./redis-data:/data
